# -*- coding: utf-8 -*-
"""03_K번째_큰_수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f4-tnOZTTlui-ORtrtr3xSYfXQg9dIbD

# K번째 큰 수

현수는 1부터 100사이의 자연수가 적힌 N장의 카드를 가지고 있다. 같은 숫자의 카드가
여러장 있을 수 있다. 현수는 이 중 3장을 뽑아 각 카드에 적힌 수를 합한 값을 기록하려고 한다. 3장을 뽑을 수 있는 모든 경우를 기록한다. 기록한 값 중 K번째로 큰 수를 출력
하는 프로그램을 작성하시오.
만약 큰 수부터 만들어진 수가 25 25 23 23 22 20 19......이고 K값이 3이라면 K번째 큰 값
은 22이다.<br><br>
**입력 설명**<br>
첫 줄에 자연수 N(3<=N<=100)과 K(1<=K<=50) 입력되고, 그 다음 줄에 N개의 카드값이 입력된다.<br><br>
**출력 설명**<br>
첫 줄에 K번째 수를 출력한다. K번째 수는 반드시 존재한다.
"""

n, k = map(int, input().split())
a = list(map(int, input().split()))
res = set()

for i in range(n):
  for j in range(i+1, n):
    for m in range(j+1, n):
      res.add(a[i]+a[j]+a[m]) # set은 append가 아니라 add
    
res = list(res)
res.sort(reverse=True)
print(res[k-1])

