# -*- coding: utf-8 -*-
"""04_최솟값_구하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRF4ZAHlG4CA0fGJHapTtaQJ_6SOBNGv
"""

arr = [5, 3, 7, 9, 2, 5, 2, 6]
arrMin = arr[0]

for x in arr:
  if x < arrMin:
    arrMin = x

print(arrMin)

arr = [5, 3, 7, 9, 2, 5, 2, 6]
arrMin = float('inf')

for i in range(len(arr)):
  if arr[i] < arrMin:
    arrMin = arr[i]
print(arrMin)

