# -*- coding: utf-8 -*-
"""05_대푯값.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6UMR_xaiMAmGeZzCT8lRm-_nVtyY7lp

# 대푯값

N명의 학생의 수학점수가 주어진다. N명의 학생들의 평균(소수 첫째자리 반올림)을 구하고,
N명의 학생 중 평균에 가장 가까운 학생은 몇 번째 학생인지 출력하는 프로그램을 작성하시오.<br>
평균과 가장 가까운 점수가 여러 개일 경우 먼저 점수가 높은 학생의 번호를 답으로 하고, 높
은 점수를 가진 학생이 여러 명일 경우 그 중 학생번호가 빠른 학생의 번호를 답으로 한다.
<br><br>
**입력설명**<br>
첫줄에 자연수 N(5<=N<=100)이 주어지고, 두 번째 줄에는 각 학생의 수학점수인 N개의 자연
수가 주어진다. 학생의 번호는 앞에서부터 1로 시작해서 N까지이다.<br><br>
**출력설명**<br>
첫줄에 평균과 평균에 가장 가까운 학생의 번호를 출력한다.
평균은 소수 첫째 자리에서 반올림한다.
"""

n = int(input())
a = list(map(int, input().split()))

avg = round(sum(a)/n)
min = 2147000000

for idx, x in enumerate(a): # enumerate는 리스트의 인덱스값과 인덱스 안의 실제값을 반환해준다.
  tmp = abs(x-avg)
  if tmp < min:
    min = tmp
    score = x
    res = idx+1 # idx가 0으로 시작하니깐
  elif tmp == min:
    if x > score: # x >= scroe가 되면 idx가 가장 큰 것이 답이 됨.
      score = x
      res = idx + 1
print(avg, res)

